// ── Setup Performance Tracker ──
// Tracks setups generated by V5 (live_setups.json) over time.
// Logs new setups, checks existing ones against current price → marks outcome.
// PURE OBSERVATIONAL — does NOT execute trades. Used to grade signal quality and learn.
//
// One-shot: node setup-tracker.js
// Daemon: node setup-tracker.js --daemon

import { writeFileSync, readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { mkLogger } from './_log-helper.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SETUPS_FILE = join(__dirname, 'live_setups.json');
const SCAN_FILE = join(__dirname, 'last_scan.json');
const HISTORY_FILE = join(__dirname, 'setup_history.json');
const STATS_FILE = join(__dirname, 'setup_stats.json');
const LOG = join(__dirname, 'setup-tracker.log');
const log = mkLogger(LOG);

function readJSON(path) {
  if (!existsSync(path)) return null;
  try { return JSON.parse(readFileSync(path, 'utf8')); } catch { return null; }
}
function writeJSON(path, data) {
  writeFileSync(path, JSON.stringify(data, null, 2));
}

// Setup expires after this many hours if not hit
const EXPIRY_HOURS = 96;  // 4 days

function makeId(s, ts) {
  return `${s.symbol}_${s.direction}_${Math.round(s.entry * 1000)}_${ts}`;
}

function checkOutcome(setup, currentPrice) {
  // Returns { status, outcome, hit_at, r_multiple }
  if (!currentPrice || !setup.entry || !setup.sl) return null;
  const isLong = setup.direction === 'LONG';
  const tp1 = setup.tp1, tp2 = setup.tp2 || setup.tp;
  const slHit = isLong ? currentPrice <= setup.sl : currentPrice >= setup.sl;
  const tp1Hit = tp1 ? (isLong ? currentPrice >= tp1 : currentPrice <= tp1) : false;
  const tp2Hit = tp2 ? (isLong ? currentPrice >= tp2 : currentPrice <= tp2) : false;
  const riskPts = Math.abs(setup.entry - setup.sl);
  const pnlPts = isLong ? (currentPrice - setup.entry) : (setup.entry - currentPrice);
  const rMul = riskPts > 0 ? +(pnlPts / riskPts).toFixed(2) : 0;
  if (slHit) return { status: 'CLOSED', outcome: 'SL_HIT', r_multiple: -1 };
  if (tp2Hit) return { status: 'CLOSED', outcome: 'TP2_HIT', r_multiple: tp2 ? +((isLong?(tp2-setup.entry):(setup.entry-tp2))/riskPts).toFixed(2) : 0 };
  if (tp1Hit) return { status: 'OPEN', outcome: 'TP1_HIT', r_multiple: rMul };  // Still open, partial win
  return { status: 'OPEN', outcome: 'PENDING', r_multiple: rMul };
}

function computeStats(history) {
  const closed = history.filter(h => h.status === 'CLOSED');
  if (closed.length === 0) return { total: 0, wins: 0, losses: 0, win_rate: 0 };
  const wins = closed.filter(h => h.outcome === 'TP2_HIT' || (h.outcome === 'TP1_HIT' && h.r_multiple > 0)).length;
  const losses = closed.filter(h => h.outcome === 'SL_HIT').length;
  const totalR = closed.reduce((a, h) => a + (h.r_multiple || 0), 0);
  const wr = closed.length > 0 ? +(wins / closed.length * 100).toFixed(1) : 0;

  // Per quality (A+, A, B, C)
  const byQuality = {};
  ['A+', 'A', 'B', 'C'].forEach(q => {
    const sub = closed.filter(h => h.quality === q);
    if (sub.length > 0) {
      const subWins = sub.filter(h => h.outcome === 'TP2_HIT').length;
      byQuality[q] = {
        total: sub.length,
        wins: subWins,
        win_rate: +(subWins / sub.length * 100).toFixed(1),
        total_r: +sub.reduce((a, h) => a + (h.r_multiple || 0), 0).toFixed(2)
      };
    }
  });

  // Per symbol
  const bySymbol = {};
  closed.forEach(h => {
    if (!bySymbol[h.symbol]) bySymbol[h.symbol] = { total: 0, wins: 0, total_r: 0 };
    bySymbol[h.symbol].total++;
    if (h.outcome === 'TP2_HIT') bySymbol[h.symbol].wins++;
    bySymbol[h.symbol].total_r += h.r_multiple || 0;
  });
  Object.keys(bySymbol).forEach(s => {
    bySymbol[s].win_rate = +(bySymbol[s].wins / bySymbol[s].total * 100).toFixed(1);
    bySymbol[s].total_r = +bySymbol[s].total_r.toFixed(2);
  });

  // Per direction
  const longSetups = closed.filter(h => h.direction === 'LONG');
  const shortSetups = closed.filter(h => h.direction === 'SHORT');
  const dirWR = (arr) => arr.length > 0 ? +(arr.filter(h => h.outcome === 'TP2_HIT').length / arr.length * 100).toFixed(1) : 0;

  return {
    total_closed: closed.length,
    total_open: history.filter(h => h.status === 'OPEN').length,
    wins,
    losses,
    win_rate: wr,
    total_r: +totalR.toFixed(2),
    avg_r_per_trade: +(totalR / closed.length).toFixed(2),
    by_quality: byQuality,
    by_symbol: bySymbol,
    long: { total: longSetups.length, win_rate: dirWR(longSetups) },
    short: { total: shortSetups.length, win_rate: dirWR(shortSetups) },
    last_updated: new Date().toISOString()
  };
}

async function run() {
  log('🔄 Tracking setups...');
  const setups = readJSON(SETUPS_FILE) || { setups: [] };
  const scan = readJSON(SCAN_FILE);
  const prices = {};
  (scan?.symbols || []).forEach(s => prices[s.symbol] = s.price);

  let history = readJSON(HISTORY_FILE) || { setups: [] };
  const existingIds = new Set(history.setups.map(s => s.id));

  // 1. Add new setups
  let newCount = 0;
  for (const s of (setups.setups || [])) {
    const id = makeId(s, setups.timestamp);
    if (existingIds.has(id)) continue;
    history.setups.push({
      id,
      first_seen: setups.timestamp,
      symbol: s.symbol,
      direction: s.direction,
      entry: s.entry,
      sl: s.sl,
      tp1: s.tp1,
      tp2: s.tp2,
      rr: s.rr,
      quality: s.quality,
      score: s.score,
      reasons: s.reasons,
      status: 'OPEN',
      outcome: 'PENDING',
      r_multiple: 0,
      market_context: setups.market_context
    });
    newCount++;
  }

  // 2. Re-check open setups against current price
  let closed = 0;
  for (const h of history.setups) {
    if (h.status !== 'OPEN') continue;
    const px = prices[h.symbol];
    if (!px) continue;
    const result = checkOutcome(h, px);
    if (!result) continue;
    h.last_price = px;
    h.last_checked = new Date().toISOString();
    h.r_multiple = result.r_multiple;
    if (result.outcome === 'TP1_HIT' && h.outcome !== 'TP1_HIT' && h.outcome !== 'TP2_HIT') {
      h.outcome = 'TP1_HIT';
      h.tp1_hit_at = new Date().toISOString();
    }
    if (result.status === 'CLOSED') {
      h.status = 'CLOSED';
      h.outcome = result.outcome;
      h.closed_at = new Date().toISOString();
      h.r_multiple = result.r_multiple;
      closed++;
    }
    // Expire setups that didn't trigger after 96h
    const ageH = (new Date() - new Date(h.first_seen)) / 3600000;
    if (h.status === 'OPEN' && ageH > EXPIRY_HOURS && (h.outcome === 'PENDING' || h.outcome === 'TP1_HIT')) {
      h.status = 'CLOSED';
      h.outcome = h.outcome === 'TP1_HIT' ? 'EXPIRED_PARTIAL' : 'EXPIRED';
      h.closed_at = new Date().toISOString();
      closed++;
    }
  }

  // 3. Cap history to last 500 setups (rolling window)
  history.setups = history.setups.slice(-500);
  history.last_updated = new Date().toISOString();
  writeJSON(HISTORY_FILE, history);

  // 4. Compute and write stats
  const stats = computeStats(history.setups);
  writeJSON(STATS_FILE, stats);

  log(`✅ +${newCount} new · ${closed} closed · total ${history.setups.length} (open ${stats.total_open}, closed ${stats.total_closed}) · WR ${stats.win_rate}%`);
  return { history, stats };
}

if (process.argv.includes('--daemon')) {
  run().catch(e => log('❌ ' + e.message));
  setInterval(() => run().catch(e => log('❌ ' + e.message)), 15 * 60 * 1000);
} else {
  run().catch(e => { log('❌ ' + e.message); process.exit(1); });
}
