// TradeBobby Desktop -- a thin Electron control panel around the existing Node dashboard.
// It does NOT reimplement anything: on launch it runs `manage.sh start` (dashboard + 19
// daemons), waits for :3333 to answer, then shows the dashboard in a window. A tray icon
// gives start/stop/restart/status without a terminal. Closing the window hides to tray so
// the daemons keep feeding data; "Stop all & Quit" is the explicit full shutdown.

const { app, BrowserWindow, Tray, Menu, nativeImage, shell, dialog } = require('electron');
const { execFile } = require('child_process');
const path = require('path');
const fs = require('fs');
const http = require('http');

// ── Resolve the dashboard dir robustly. In dev it sits next to desktop/. Once packaged
// into a .app, __dirname is inside the bundle, so we can't use "../dashboard". Order:
//   1) TB_DASH_DIR env var, 2) saved choice (userData/dashboard-path.txt),
//   3) dev sibling ../dashboard, 4) the known repo path, 5) prompt the user to locate it.
// The saved-choice + prompt make it survive a repo move (which already broke the crontab once).
const DEFAULT_REPO_DASH = '/Users/neo/Documents/VsCodeN30/GIT_PUBLIC_SoCloseSociety/TradeBobby/dashboard';
function savedPathFile() { return path.join(app.getPath('userData'), 'dashboard-path.txt'); }
function isDashDir(d) { return d && fs.existsSync(path.join(d, 'manage.sh')); }

function resolveDashDir() {
  const candidates = [
    process.env.TB_DASH_DIR,
    (() => { try { return fs.readFileSync(savedPathFile(), 'utf8').trim(); } catch { return null; } })(),
    path.resolve(__dirname, '..', 'dashboard'),
    DEFAULT_REPO_DASH
  ];
  for (const c of candidates) if (isDashDir(c)) return c;
  return null;
}

let DASH_DIR = resolveDashDir();
let MANAGE = DASH_DIR ? path.join(DASH_DIR, 'manage.sh') : null;
const URL = 'http://localhost:3333';
const LIVE_URL = URL + '/live';

let win = null;
let tray = null;
let quitting = false;

// ── run a manage.sh subcommand, return output ──
function manage(cmd, cb) {
  if (!MANAGE) { if (cb) cb(new Error('dashboard not located'), ''); return; }
  execFile('/bin/bash', [MANAGE, cmd], { cwd: DASH_DIR, timeout: 60000 }, (err, stdout, stderr) => {
    if (cb) cb(err, (stdout || '') + (stderr || ''));
  });
}

// ── ask the user to locate the dashboard folder, persist the choice ──
function promptForDashDir() {
  const picked = dialog.showOpenDialogSync({
    title: 'Locate the TradeBobby dashboard folder',
    message: 'Select the folder that contains manage.sh (…/TradeBobby/dashboard)',
    properties: ['openDirectory']
  });
  if (picked && picked[0] && isDashDir(picked[0])) {
    DASH_DIR = picked[0];
    MANAGE = path.join(DASH_DIR, 'manage.sh');
    try { fs.writeFileSync(savedPathFile(), DASH_DIR); } catch {}
    return true;
  }
  return false;
}

// ── poll until the dashboard HTTP answers (server just started) ──
function waitForServer(timeoutMs, cb) {
  const deadline = Date.now() + timeoutMs;
  const tick = () => {
    const req = http.get(URL, res => { res.destroy(); cb(true); });
    req.on('error', () => {
      if (Date.now() > deadline) return cb(false);
      setTimeout(tick, 500);
    });
    req.setTimeout(2000, () => req.destroy());
  };
  tick();
}

function createWindow() {
  win = new BrowserWindow({
    width: 1440,
    height: 900,
    minWidth: 900,
    minHeight: 600,
    title: 'TradeBobby',
    backgroundColor: '#0a0c0f',
    webPreferences: { contextIsolation: true },
    show: false
  });
  win.loadURL(URL);
  win.once('ready-to-show', () => win.show());
  // External links (news sources etc.) open in the real browser, not inside the app.
  win.webContents.setWindowOpenHandler(({ url }) => {
    if (!url.startsWith(URL)) { shell.openExternal(url); return { action: 'deny' }; }
    return { action: 'allow' };
  });
  // Close = hide to tray (daemons keep running). Real quit goes through the tray menu.
  win.on('close', e => {
    if (!quitting) { e.preventDefault(); win.hide(); }
  });
}

// ── tray icon (generated by gen-icons.js into assets/) ──
function trayIcon() {
  const img = nativeImage.createFromPath(path.join(__dirname, 'assets', 'tray.png'));
  return img.isEmpty() ? nativeImage.createEmpty() : img.resize({ width: 18, height: 18 });
}

function buildMenu(statusText) {
  return Menu.buildFromTemplate([
    { label: statusText || 'TradeBobby', enabled: false },
    { type: 'separator' },
    { label: 'Open Dashboard', click: () => showDashboard() },
    { label: 'Open Live Orderflow', click: () => shell.openExternal(LIVE_URL) },
    { type: 'separator' },
    { label: 'Start all', click: () => manage('start', () => refreshStatus()) },
    { label: 'Restart all', click: () => manage('restart', () => refreshStatus()) },
    { label: 'Stop all daemons', click: () => manage('stop', () => refreshStatus()) },
    { label: 'Refresh status', click: () => refreshStatus() },
    { label: 'Locate dashboard folder...', click: () => { if (promptForDashDir()) { manage('start', () => refreshStatus()); } } },
    { type: 'separator' },
    { label: 'Quit (leave daemons running)', click: () => { quitting = true; app.quit(); } },
    { label: 'Stop all & Quit', click: () => {
        manage('stop', () => { quitting = true; app.quit(); });
      } }
  ]);
}

function showDashboard() {
  if (!win) createWindow();
  else { win.show(); win.focus(); }
}

// ── count green daemons for the tray header ──
function refreshStatus() {
  manage('status', (err, out) => {
    const green = (out.match(/🟢/g) || []).length;
    const red = (out.match(/🔴/g) || []).length;
    const label = `● ${green} up / ${red} down`;
    if (tray) {
      tray.setToolTip(`TradeBobby -- ${green} up, ${red} down`);
      tray.setContextMenu(buildMenu(label));
    }
  });
}

app.whenReady().then(() => {
  tray = new Tray(trayIcon());
  tray.setToolTip('TradeBobby -- starting...');
  tray.setContextMenu(buildMenu('Starting...'));
  tray.on('click', () => showDashboard());

  // If the dashboard folder wasn't found (e.g. repo moved, or first run of the packaged
  // app), ask the user to point at it before trying to start anything.
  if (!MANAGE) {
    const ok = promptForDashDir();
    if (!ok) {
      dialog.showErrorBox('TradeBobby',
        'Could not find the dashboard folder (the one containing manage.sh).\n' +
        'The app will stay in the tray -- use "Locate dashboard" or set TB_DASH_DIR.');
    }
  }

  // Start the whole system, then open the dashboard once :3333 answers.
  manage('start', () => {
    waitForServer(25000, ok => {
      if (ok) { createWindow(); refreshStatus(); }
      else {
        dialog.showErrorBox('TradeBobby',
          'The dashboard did not answer on :3333 within 25s.\n' +
          'Open a terminal and run:  bash ' + MANAGE + ' status');
      }
    });
  });

  // Keep the tray status live.
  setInterval(refreshStatus, 30000);

  app.on('activate', () => showDashboard());
});

// Hiding to tray means "no windows" is normal; don't quit.
app.on('window-all-closed', e => { /* stay alive in tray */ });
